### ISSUE TITLE
package.jsonのライブラリ依存を整理したほうがいいと思います。

### ISSUE THREAD

**Issue by InoueKenichi** [Koya-SI/React#17]
開発には直接影響はない部分ですが、配布や、本番機でビルドする際に、関係性を知らないと余分なサイズや、足りないモジュールで実行エラーになると思います。

https://github.com/Koya-SI/React/blob/main/my-app/package.json

dependenciesは、実行時に依存関係があるパッケージを登録するセクションです。
本番機にビルドして配置するなどの際に、このパッケージに登録されていない場合は、実行エラーになります。

下記のものは、開発時にしか利用しないものだと思われます。
https://github.com/Koya-SI/React/blob/main/my-app/package.json#L6-L10
https://github.com/Koya-SI/React/blob/main/my-app/package.json#L14-L15

devDependenciesは、開発中に依存しているパッケージを登録するセクションです。
テスト用などで利用するさいに必要なモジュールはここに配置します。
本番機でビルドして配置する際は、こちらに登録したモジュールは省かれるのでサイズが小さくなります。
https://github.com/Koya-SI/React/blob/main/my-app/package.json#L44

**Comment by InoueKenichi** [comment]
これは実施済み？

**Comment by Koya-SI** [comment]
こちらも修正して、コミット致しました。
https://github.com/Koya-SI/React/pull/25/commits/0e83136e1fb1db221493eba021339d7cd7b08f0d

**Comment by InoueKenichi** [comment]
恐らくpackage-lock.jsonも更新する必要があると思われます。

npm install
を実施すると更新されると思われます。

**Comment by Koya-SI** [comment]
npm install で更新致しました。
https://github.com/Koya-SI/React/pull/25/commits/16687e2d7142250769db4ed178f2be7c9b9e1583
