### ISSUE TITLE
追加機能

### ISSUE THREAD

**Issue by InoueKenichi** [Koya-SI/React#18]
1. 実行履歴リストの形式（列、行）で表示するように変更すること。
2. 現在実行されている項目を太字で表示すること。
3. ボードを書き直して、ハードコーディングする代わりに2つのループを使用して正方形を作成すること。
4. 実行履歴を昇順または降順で並べ替えることができるトグルボタンを追加します。
5. 勝敗が決定した場合、勝った3つの四角をハイライトします。
6. 誰も勝てない場合は、引き分けの結果についてのメッセージを表示します。

**Comment by InoueKenichi** [comment]
FIY: https://reactjs.org/tutorial/tutorial.html#wrapping-up

**Comment by InoueKenichi** [comment]
今回のPRで、追加機能は完了したという認識で間違いない？

**Comment by Koya-SI** [comment]
ご確認ありがとうございます。その認識で間違いありません。
